import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Textbook sidebar structure based on the spec
  textbookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro', 'overview'],
    },
    {
      type: 'category',
      label: 'Physical AI Fundamentals',
      items: [
        'physical-ai/introduction',
        'physical-ai/perception',
        'physical-ai/reasoning',
        'physical-ai/action',
      ],
    },
    {
      type: 'category',
      label: 'Humanoid Robotics',
      items: [
        'humanoid-robotics/introduction',
        'humanoid-robotics/design',
        'humanoid-robotics/control',
        'humanoid-robotics/applications',
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action Systems',
      items: [
        'vla-systems/introduction',
        'vla-systems/integration',
        'vla-systems/applications',
      ],
    },
    {
      type: 'category',
      label: 'ROS 2 Integration',
      items: [
        'ros2/introduction',
        'ros2/setup',
        'ros2/examples',
      ],
    },
    {
      type: 'category',
      label: 'AI Assistant Guide',
      items: [
        'ai-assistant/using-full-book-qa',
        'ai-assistant/using-selected-text-qa',
        'ai-assistant/personalization',
      ],
    },
  ],
};

export default sidebars;
