openapi: 3.0.0
info:
  title: AI-Native Textbook Platform API
  version: 1.0.0
  description: API for the Physical AI & Humanoid Robotics textbook platform
servers:
  - url: https://api.textbook-platform.com
    description: Production server
  - url: http://localhost:8000
    description: Development server

paths:
  /auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                provider:
                  type: string
                  enum: [email, google, github]
              required:
                - email
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Invalid credentials

  /content:
    get:
      summary: List textbook content
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
        - name: content_type
          in: query
          schema:
            type: string
        - name: difficulty
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of content items
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/TextbookContent'
                  total:
                    type: integer

  /content/{id}:
    get:
      summary: Get specific content
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Content item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextbookContent'
        '404':
          description: Content not found

  /ai/qa:
    post:
      summary: Full-book Q&A
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
            properties:
              query:
                type: string
              user_id:
                type: string
                format: uuid
            required:
              - query
      responses:
        '200':
          description: AI response
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                  sources:
                    type: array
                    items:
                      type: object
                      properties:
                        content_id:
                          type: string
                        title:
                          type: string
                        relevance_score:
                          type: number
                  confidence:
                    type: number

  /ai/qa-selected:
    post:
      summary: Selected-text Q&A
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                selected_content_ids:
                  type: array
                  items:
                    type: string
                    format: uuid
                user_id:
                  type: string
                  format: uuid
              required:
                - query
                - selected_content_ids
      responses:
        '200':
          description: AI response based on selected text
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIResponse'

  /user/progress:
    get:
      summary: Get user progress
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: User progress
          content:
            application/json:
              schema:
                type: object
                properties:
                  progress:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserProgress'
    post:
      summary: Update user progress
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProgress'
      responses:
        '200':
          description: Progress updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProgress'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        username:
          type: string
        role:
          type: string
          enum: [student, faculty, admin]
        created_at:
          type: string
          format: date-time
      required:
        - id
        - email
        - role

    TextbookContent:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        content_type:
          type: string
          enum: [text, code, figure, simulation, video, interactive]
        content:
          type: string
        difficulty_level:
          type: string
          enum: [beginner, intermediate, advanced]
        prerequisites:
          type: array
          items:
            type: string
            format: uuid
        tags:
          type: array
          items:
            type: string
        parent_id:
          type: string
          format: uuid
        content_path:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - title
        - content_type

    UserProgress:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        content_id:
          type: string
          format: uuid
        status:
          type: string
          enum: [not_started, in_progress, completed]
        completion_percentage:
          type: number
          minimum: 0
          maximum: 100
        time_spent:
          type: integer
        last_accessed_at:
          type: string
          format: date-time
      required:
        - id
        - user_id
        - content_id
        - status

    AIResponse:
      type: object
      properties:
        answer:
          type: string
        sources:
          type: array
          items:
            type: object
            properties:
              content_id:
                type: string
              title:
                type: string
              relevance_score:
                type: number
        confidence:
          type: number
          minimum: 0
          maximum: 1
      required:
        - answer
        - sources
        - confidence